import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Badge, Button, Form, Modal, Spinner } from 'react-bootstrap';
import { BoxArrowInDown, CheckCircle, Diagram3, Link45deg, PlusCircle, ShieldLock, XCircle } from 'react-bootstrap-icons';
import apiClient from '../../services/api';
import './HospitalIntegrationHub.css';

const emptySystem = { name: '', providerType: 'rest', direction: 'bidirectional', baseUrl: '', authType: 'none', secretKeyRef: '', status: 'inactive' };
const label = { rest: 'REST API', webhook: 'Webhook', fhir: 'FHIR (preparado)', hl7: 'HL7 (preparado)', active: 'Ativo', inactive: 'Inativo', matched: 'Vinculado', pending_review: 'Revisão pendente', rejected: 'Rejeitado', success: 'Sucesso', failed: 'Falha', processed: 'Processado', received: 'Recebido' };
const date = (value) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';

export default function HospitalIntegrationHub({ hospitalId, canManage }) {
  const [hub, setHub] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [show, setShow] = useState(false); const [saving, setSaving] = useState(false); const [form, setForm] = useState(emptySystem);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setHub((await apiClient.get(`/hospitals/${hospitalId}/integrations`)).data); } catch (e) { setError(e.response?.data?.error || 'Não foi possível carregar o Integration Hub.'); } finally { setLoading(false); } }, [hospitalId]);
  useEffect(() => { load(); }, [load]);
  const stats = useMemo(() => ({ active: hub?.systems.filter((item) => item.status === 'active').length || 0, pending: hub?.identifiers.filter((item) => item.matching_status === 'pending_review').length || 0, failures: hub?.logs.filter((item) => item.status === 'failed').length || 0 }), [hub]);
  const create = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { await apiClient.post(`/hospitals/${hospitalId}/integrations/systems`, form); setShow(false); setForm(emptySystem); await load(); } catch (e) { setError(e.response?.data?.error || 'Não foi possível cadastrar o conector.'); } finally { setSaving(false); } };
  const toggle = async (system) => { setError(''); try { await apiClient.patch(`/hospitals/${hospitalId}/integrations/systems/${system.id}`, { status: system.status === 'active' ? 'inactive' : 'active' }); await load(); } catch (e) { setError(e.response?.data?.error || 'Não foi possível alterar o conector.'); } };
  if (loading && !hub) return <div className="ach-integration-state" role="status" aria-live="polite"><Spinner animation="border" aria-hidden="true" /><span>Carregando interoperabilidade…</span></div>;
  return <section className="ach-integration">
    <header><div><span>INTEROPERABILIDADE HOSPITALAR</span><h2>Integration Hub</h2><p>Conecte HIS/PEP sem duplicar prontuários ou transformar o AutisConnect em ERP.</p></div>{canManage ? <Button onClick={() => setShow(true)}><PlusCircle /> Novo conector</Button> : null}</header>
    {error ? <Alert variant="danger" dismissible onClose={() => setError('')}>{error}<Button size="sm" variant="outline-danger" onClick={load}>Tentar novamente</Button></Alert> : null}
    <div className="ach-integration__stats"><article><Diagram3 /><span><strong>{hub?.systems.length || 0}</strong>Conectores</span></article><article><CheckCircle /><span><strong>{stats.active}</strong>Ativos</span></article><article><Link45deg /><span><strong>{hub?.identifiers.length || 0}</strong>IDs mapeados</span></article><article><ShieldLock /><span><strong>{stats.pending}</strong>Revisões pendentes</span></article></div>
    <div className="ach-integration__grid"><article className="ach-integration__panel"><div className="ach-integration__title"><h3>Sistemas externos</h3><small>Segredos permanecem no ambiente seguro.</small></div><div className="ach-integration__systems">{hub?.systems.map((system) => <div key={system.id}><i className={`is-${system.status}`}><Diagram3 /></i><span><strong>{system.name}</strong><small>{label[system.provider_type] || system.provider_type} · {system.direction}</small></span><Badge bg={system.status === 'active' ? 'success' : 'secondary'}>{label[system.status] || system.status}</Badge>{canManage ? <Button size="sm" variant="outline-primary" onClick={() => toggle(system)}>{system.status === 'active' ? 'Pausar' : 'Ativar'}</Button> : null}</div>)}{!hub?.systems.length ? <p className="ach-integration__empty">Nenhum conector configurado.</p> : null}</div></article>
      <article className="ach-integration__panel"><div className="ach-integration__title"><h3>Sincronizações recentes</h3><small>{stats.failures ? `${stats.failures} falha(s) exigem atenção` : 'Operação sem falhas recentes'}</small></div><div className="ach-integration__timeline">{hub?.logs.slice(0, 8).map((item) => <div key={item.id}>{item.status === 'success' ? <CheckCircle className="is-ok" /> : <XCircle className="is-error" />}<span><strong>{item.operation}</strong><small>{item.direction} · {date(item.created_at)}</small></span><code>{`${item.correlation_id}`.slice(0, 8)}</code></div>)}{!hub?.logs.length ? <p className="ach-integration__empty">Ainda não há sincronizações registradas.</p> : null}</div></article>
      <article className="ach-integration__panel ach-integration__panel--wide"><div className="ach-integration__title"><h3>Identidade e ingestão</h3><small>Matching por nome nunca é automático.</small></div><div className="ach-integration__table"><table><thead><tr><th>Tipo</th><th>ID externo</th><th>ID AutisConnect</th><th>Status</th><th>Revisado</th></tr></thead><tbody>{hub?.identifiers.slice(0, 10).map((item) => <tr key={item.id}><td>{item.resource_type}</td><td>{item.external_id}</td><td>{item.internal_id || '—'}</td><td><Badge bg={item.matching_status === 'matched' ? 'success' : item.matching_status === 'rejected' ? 'danger' : 'warning'}>{label[item.matching_status] || item.matching_status}</Badge></td><td>{date(item.reviewed_at)}</td></tr>)}</tbody></table>{!hub?.identifiers.length ? <p className="ach-integration__empty">Nenhum identificador externo recebido.</p> : null}</div></article>
    </div>
    <footer><ShieldLock /><span><strong>Limite intencional:</strong> este hub guarda metadados de interoperabilidade, hashes e estados; o conteúdo clínico permanece nos sistemas de origem e nos módulos clínicos já existentes.</span></footer>
    <Modal show={show} onHide={() => setShow(false)} centered><Form onSubmit={create}><Modal.Header closeButton><Modal.Title>Novo conector</Modal.Title></Modal.Header><Modal.Body className="ach-integration__form"><Form.Group><Form.Label>Nome do sistema</Form.Label><Form.Control required maxLength={160} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Form.Group><Form.Group><Form.Label>Provider</Form.Label><Form.Select value={form.providerType} onChange={(e) => setForm({ ...form, providerType: e.target.value })}><option value="rest">REST API</option><option value="webhook">Webhook</option><option value="fhir">FHIR (arquitetura)</option><option value="hl7">HL7 (arquitetura)</option></Form.Select></Form.Group><Form.Group><Form.Label>Direção</Form.Label><Form.Select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })}><option value="bidirectional">Bidirecional</option><option value="inbound">Entrada</option><option value="outbound">Saída</option></Form.Select></Form.Group><Form.Group><Form.Label>URL base</Form.Label><Form.Control type="url" value={form.baseUrl} onChange={(e) => setForm({ ...form, baseUrl: e.target.value })} /></Form.Group><Form.Group><Form.Label>Referência do segredo no ambiente</Form.Label><Form.Control placeholder="HOSPITAL_HIS_WEBHOOK_SECRET" value={form.secretKeyRef} onChange={(e) => setForm({ ...form, secretKeyRef: e.target.value })} /><Form.Text>Nunca informe o segredo; apenas o nome da variável segura.</Form.Text></Form.Group></Modal.Body><Modal.Footer><Button variant="outline-secondary" onClick={() => setShow(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? <Spinner size="sm" /> : <BoxArrowInDown />} Cadastrar</Button></Modal.Footer></Form></Modal>
  </section>;
}
