import { useEffect, useState } from 'react';
import { Alert, Button, Card, Col, Form, Pagination, Row, Spinner, Table } from 'react-bootstrap';
import apiClient from '../services/api';
const AuditoriaExecutiva = () => { const [data, setData] = useState({ items: [], pagination: { page: 1, totalPages: 1 } }); const [filters, setFilters] = useState({ search: '', operation: '', startDate: '', endDate: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async (page = 1) => { setLoading(true); try { const response = await apiClient.get('/executive/audit/logs', { params: { ...filters, page, limit: 20 } }); setData(response.data); setError(''); } catch (requestError) { setError(requestError.response?.data?.error || 'Não foi possível carregar a auditoria.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  return <><Card className="mb-4"><Card.Body><Card.Title>Dashboard Administrativo - Auditoria</Card.Title><Row className="g-2"><Col md={4}><Form.Control placeholder="Pesquisar rota ou tabela" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} /></Col><Col md={2}><Form.Select value={filters.operation} onChange={(event) => setFilters({ ...filters, operation: event.target.value })}><option value="">Operações</option>{['GET', 'POST', 'PUT', 'DELETE'].map((operation) => <option key={operation}>{operation}</option>)}</Form.Select></Col><Col md={2}><Form.Control type="date" value={filters.startDate} onChange={(event) => setFilters({ ...filters, startDate: event.target.value })} /></Col><Col md={2}><Form.Control type="date" value={filters.endDate} onChange={(event) => setFilters({ ...filters, endDate: event.target.value })} /></Col><Col md={2}><Button className="w-100" onClick={() => load(1)}>Filtrar</Button></Col></Row></Card.Body></Card>{error && <Alert variant="danger">{error}</Alert>}<Card><Card.Body>{loading ? <div className="text-center py-4"><Spinner animation="border" /></div> : <><Table responsive hover><thead><tr><th>Data/Hora</th><th>Usuário</th><th>IP</th><th>Operação</th><th>Tabela</th><th>Registro</th><th>Rota</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString('pt-BR')}</td><td>{item.user_id || '—'}</td><td>{item.ip_address || '—'}</td><td>{item.operation}</td><td>{item.table_name || '—'}</td><td>{item.record_id || '—'}</td><td>{item.route}</td></tr>)}{!data.items.length && <tr><td colSpan="7" className="text-center">Nenhuma operação registrada.</td></tr>}</tbody></Table><Pagination>{Array.from({ length: data.pagination.totalPages || 1 }, (_, index) => <Pagination.Item key={index + 1} active={data.pagination.page === index + 1} onClick={() => load(index + 1)}>{index + 1}</Pagination.Item>)}</Pagination></>}</Card.Body></Card></>;
};
export default AuditoriaExecutiva;
