import { useEffect, useState } from 'react';
import { Alert, Button, Card, Col, Form, Row, Spinner, Table } from 'react-bootstrap';
import apiClient from '../services/api';
const initial = { name: '', description: '', baseCompetence: new Date().toISOString().slice(0, 7), projectedRevenue: '', projectedExpenses: '', projectedPayroll: '', projectedProfessionals: '', projectedPatients: '', projectedAppointments: '' };
const money = (value) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function FiscalScenariosPanel() {
  const [form, setForm] = useState(initial); const [items, setItems] = useState([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState(null);
  const load = async () => { setLoading(true); try { const { data } = await apiClient.get('/executive/fiscal/scenarios'); setItems(Array.isArray(data) ? data : []); setError(''); } catch (requestError) { setError(requestError.response?.data?.error || 'Não foi possível carregar cenários fiscais.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const change = (event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value })); };
  const create = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const { data } = await apiClient.post('/executive/fiscal/scenarios', form); setResult(data); setForm(initial); await load(); } catch (requestError) { setError(requestError.response?.data?.error || 'Não foi possível criar o cenário fiscal.'); } finally { setSaving(false); } };
  const parse = (value) => { try { return typeof value === 'string' ? JSON.parse(value) : value; } catch { return null; } };
  return <Row className="g-4 mt-1"><Col xl={5}><Card className="h-100"><Card.Body><Card.Title className="h5">Novo cenário fiscal</Card.Title><p className="small text-muted">A simulação não altera contas, recebimentos ou lançamentos reais.</p>{error && <Alert variant="danger">{error}</Alert>}<Form onSubmit={create}><Row className="g-3"><Col md={12}><Form.Control name="name" placeholder="Nome do cenário" value={form.name} onChange={change} required /></Col><Col md={12}><Form.Control name="description" placeholder="Descrição opcional" value={form.description} onChange={change} /></Col><Col md={6}><Form.Label>Competência base</Form.Label><Form.Control name="baseCompetence" type="month" value={form.baseCompetence} onChange={change} required /></Col><Col md={6}><Form.Label>Receita projetada</Form.Label><Form.Control name="projectedRevenue" type="number" min="0" step="0.01" value={form.projectedRevenue} onChange={change} required /></Col><Col md={6}><Form.Label>Despesas projetadas</Form.Label><Form.Control name="projectedExpenses" type="number" min="0" step="0.01" value={form.projectedExpenses} onChange={change} /></Col><Col md={6}><Form.Label>Folha projetada</Form.Label><Form.Control name="projectedPayroll" type="number" min="0" step="0.01" value={form.projectedPayroll} onChange={change} /></Col><Col md={12}><Button type="submit" disabled={saving}>{saving ? 'Simulando...' : 'Criar cenário'}</Button></Col></Row></Form>{result && <Alert variant={Number(result.projectedProfit) >= 0 ? 'success' : 'warning'} className="mt-3 mb-0"><strong>Resultado projetado: {money(result.projectedProfit)}</strong><br />Tributos estimados: {money(result.projectedTaxes)}<br />Margem: {Number(result.projectedMargin || 0).toLocaleString('pt-BR')}%</Alert>}</Card.Body></Card></Col><Col xl={7}><Card className="h-100"><Card.Body><div className="d-flex justify-content-between"><Card.Title className="h5">Cenários salvos</Card.Title><Button size="sm" variant="outline-secondary" onClick={load} disabled={loading}>Atualizar</Button></div>{loading ? <div className="text-center py-4"><Spinner size="sm" animation="border" /></div> : <div className="table-responsive"><Table hover size="sm"><thead><tr><th>Cenário</th><th>Base</th><th>Receita</th><th>Resultado</th><th>Margem</th></tr></thead><tbody>{items.length ? items.map((item) => { const calculated = parse(item.calculated_result) || {}; return <tr key={item.id}><td><strong>{item.name}</strong><small className="d-block text-muted">{item.description || 'Sem descrição'}</small></td><td>{String(item.base_competence).slice(0, 7)}</td><td>{money(item.projected_revenue)}</td><td>{money(calculated.projectedProfit)}</td><td>{Number(calculated.projectedMargin || 0).toLocaleString('pt-BR')}%</td></tr>; }) : <tr><td colSpan="5" className="text-center text-muted py-4">Nenhum cenário criado.</td></tr>}</tbody></Table></div>}</Card.Body></Card></Col></Row>;
}
