import { useEffect, useState } from 'react';
import { Alert, Badge, Button, Card, Spinner, Table } from 'react-bootstrap';
import apiClient from '../services/api';
const money = (value) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function FiscalDataValidationPanel({ competence }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const response = await apiClient.get('/executive/fiscal/validation', { params: { competence } }); setData(response.data); setError(''); } catch (requestError) { setError(requestError.response?.data?.error || 'Não foi possível validar os dados financeiros.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [competence]);
  return <Card className="mt-4"><Card.Body><div className="d-flex justify-content-between gap-2 flex-wrap"><div><Card.Title className="h5">Validação de dados financeiros</Card.Title><p className="text-muted small mb-0">Somente recebimentos com status recebido, data de recebimento e valor positivo entram no regime de caixa.</p></div><Button variant="outline-secondary" size="sm" onClick={load} disabled={loading}>Validar novamente</Button></div>{error && <Alert variant="danger" className="mt-3 mb-0">{error}</Alert>}{loading ? <div className="text-center py-3"><Spinner size="sm" animation="border" /></div> : <>{data && <p className="mt-3 mb-2"><Badge bg={data.status === 'ready' ? 'success' : 'warning'}>{data.status === 'ready' ? 'Dados prontos para cálculo' : 'Revisão necessária'}</Badge> <span className="ms-2">{data.validReceived.count} recebimento(s) válido(s): <strong>{money(data.validReceived.amount)}</strong></span></p>}<Table responsive size="sm" className="mb-0"><thead><tr><th>Verificação</th><th>Ocorrências</th><th>Impacto</th></tr></thead><tbody>{data?.issues?.length ? data.issues.map((issue) => <tr key={issue.key}><td>{issue.title}</td><td>{issue.count}</td><td>{issue.message}</td></tr>) : <tr><td colSpan="3" className="text-center text-muted py-3">Nenhuma inconsistência encontrada.</td></tr>}</tbody></Table></>}</Card.Body></Card>;
}
