import { useEffect, useState } from 'react';
import { Alert, Button, Card, Form, Modal, Spinner, Table } from 'react-bootstrap';
import apiClient from '../services/api';
import ContractOptions from './ContractOptions';

const initial = { contract_type: '', payout_type: '', revenue_share_percentage: '', hourly_rate: '', session_rate: '', salary: '', start_date: '', end_date: '' };
export default function GestaoProfissionaisContractManagement() {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [contract, setContract] = useState(initial); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const { data } = await apiClient.get('/executive/professionals', { params: { limit: 100 } }); setItems(data.items || []); } catch (e) { setError(e.response?.data?.error || 'Não foi possível carregar os profissionais.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const consult = async (item) => { try { const { data } = await apiClient.get(`/executive/professionals/${item.id}`); setSelected({ ...item, detail: data }); } catch (e) { setError(e.response?.data?.error || 'Não foi possível consultar o profissional.'); } };
  const edit = () => { const value = selected.detail?.contract || {}; setContract({ ...initial, ...Object.fromEntries(Object.keys(initial).map((key) => [key, value[key] ?? ''])) }); setShow(true); };
  const save = async () => { try { await apiClient.put(`/executive/professionals/${selected.id}/contract`, contract); setShow(false); setSuccess('Contrato atualizado.'); consult(selected); } catch (e) { setError(e.response?.data?.error || 'Não foi possível salvar o contrato.'); } };
  if (loading) return <div className="text-center py-5"><Spinner animation="border" /></div>;
  return <><h2 className="h4 mb-3">Gestão dos Profissionais</h2>{error && <Alert variant="danger">{error}</Alert>}{success && <Alert variant="success">{success}</Alert>}<Card><Card.Body><Table responsive hover><thead><tr><th>Profissional</th><th>Especialidade</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.nome_completo}</td><td>{item.especialidade || 'Não informada'}</td><td><Button size="sm" onClick={() => consult(item)}>Consultar</Button></td></tr>)}</tbody></Table></Card.Body></Card>{selected && <Card className="mt-4"><Card.Body><div className="d-flex justify-content-between"><Card.Title>{selected.nome_completo}</Card.Title><Button onClick={edit}>Editar Contrato</Button></div><Table className="mt-3"><tbody>{Object.entries({ contract_type: 'Tipo de contrato', payout_type: 'Tipo de repasse', revenue_share_percentage: 'Percentual', hourly_rate: 'Valor hora', session_rate: 'Valor sessão', salary: 'Salário' }).map(([key,label]) => <tr key={key}><th>{label}</th><td>{selected.detail?.contract?.[key] || 'Não informado'}</td></tr>)}</tbody></Table></Card.Body></Card>}<Modal show={show} onHide={() => setShow(false)}><Modal.Header closeButton><Modal.Title>Editar Contrato</Modal.Title></Modal.Header><Modal.Body>{Object.entries({ contract_type: 'Tipo de contrato', payout_type: 'Tipo de repasse', revenue_share_percentage: 'Percentual', hourly_rate: 'Valor hora', session_rate: 'Valor sessão', salary: 'Salário', start_date: 'Início', end_date: 'Fim' }).map(([key,label]) => <Form.Group className="mb-2" key={key}><Form.Label>{label}</Form.Label><ContractOptions field={key} value={contract[key]} onChange={(e) => setContract({ ...contract, [key]: e.target.value })} /></Form.Group>)}</Modal.Body><Modal.Footer><Button variant="secondary" onClick={() => setShow(false)}>Cancelar</Button><Button onClick={save}>Salvar</Button></Modal.Footer></Modal></>;
}
